trigger:
  branches:
    include:
      - master   # triggers only on master

pool:
  name: Default   # uses your default self-hosted agent pool

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet latest'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/WebApi/bin/$(buildConfiguration)/netcoreapp3.1'
    ArtifactName: 'WebApiApp'
    publishLocation: 'Container'
